version: "3.9"

services:
  ai-module:
    container_name: ai-module
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    #expose:
    #  - "8000"            
    #ports:
    #  - "8000:8000"
    restart: unless-stopped
    networks:
      - ai-net

  nginx:
    container_name: ai-nginx
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - ai-module
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # конфиг nginx
      - ~/.nginx/conf.d:/etc/nginx/conf.d:ro
      #- ./nginx/conf.d:/etc/nginx/conf.d:ro
      # сертификаты
      - ~/letsencrypt:/etc/letsencrypt:ro
      # - ./nginx/certs:/etc/nginx/certs:ro
      # опционально: логи
      #- ./nginx/logs:/var/log/nginx
    networks:
      - ai-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/hc"]
      interval: 30s
      timeout: 3s
      retries: 3    

networks:
  ai-net:
    driver: bridge
